#!/bin/bash
if [ "$1" == "--help" ] || [ -z "$1" ] || [ -z "$2" ]; then
  echo "Usage generator [type] [proyect name]"
  echo "Aviable Generators types:"
  echo "    avr -> Basic AVR proyect with easyavr lib and git version control."
else
  mkdir $PWD/$2
  cp -ru ~/.scripts/templates/$1/* $PWD/$2
  cd $PWD/$2
  git init
  git add .
  git commit -a -m 'Initial Commit'
  cd ..
  echo "Proyect $2 Created"
fi
