#!/bin/bash
if [ "$1" == "--help" ] || [ -z "$1" ] || [ -z "$2" ]; then
  echo "Usage generator [type] [proyect name] <options>"
  echo "Aviable Generators types:"
  echo "    avr -> Basic AVR proyect with AVRDuino lib and git version control."
  echo "    maraton -> Python Excersise with tests for programming marathons"
  echo ""
  echo "OPTIONS: "
  echo "    --git 	: git repo creation"
else
  mkdir $PWD/$2
  shopt -s dotglob
  cp -ru ~/.scripts/proyect-generator/templates/$1/* $PWD/$2

  if [ "$1" == "avr" ]; then

    if [ "$3" == "--git" ]; then
      cd $PWD/$2
      git init
      cd lib
      git submodule add git@github.com:Waaflee/AVRDuino.git
      cd ..
      git add .
      git commit -a -m 'Initial Commit'
      cd ..
    else
      echo "no -git option, skipping git repo initialization..."
      cd $PWD/$2/lib
      if [ -d ../.git ] || [ -d ../../.git ] || [ -d ../../../.git ]; then
        git submodule add git@github.com:Waaflee/AVRDuino.git
      else
        git clone git@github.com:Waaflee/AVRDuino.git
      fi
    fi
    
fi
  echo "Proyect $2 Created"
fi
