#!/bin/bash
if [ -z $1 ]; then 
	echo "Usage: avr [operation]"
	echo "OPERATIONS:"
	echo "		new 	: Generate new files (only headers currently)"
	echo "		update 	: Fetchs latest version of easyavr lib from github"
fi

if [ "$1" == "new" ]; then
	select wen in "header" 
	do
		case "$wen" in
		  header)
		    echo "Header name?"
		    read word
		    if [ -d ./lib/custom ]; then
		      echo "lib/custom directory already exists skipping..."
		    else
		      mkdir ./lib/custom
		    fi
		    echo "#pragma once" >> ./lib/custom/"$word".h
		    echo "#import $word.h" >> ./lib/custom/"$word".c
		    echo "remember to add ./lib/custom/$word.c to ardup script"
		esac
		break
	done
	echo "Done!"
fi

if [ "$1" == "update" ]; then
	cd ~/.scripts
	git pull
	cp -ru templates/avr/lib/easyavr/* $OLDPWD/lib/easyavr
	cd -
fi
