#!/bin/bash
select wen in "header" 
do
	case "$wen" in
	  header)
	    echo "Header name?"
	    read word
	    if [ -d ./lib/custom ]; then
	      echo "lib/custom directory already exists skipping..."
	    else
	      mkdir ./lib/custom
	    fi
	    echo "#pragma once" >> ./lib/custom/"$word".h
	    echo "#import $word.h" >> ./lib/custom/"$word".c
	    echo "remember to add ./lib/custom/$word.c to ardup script"
	esac
	break
done
echo "Done!"
